use_frameworks!

target 'Cidaas_Example' do
  pod 'Cidaas', :path => '../'
  pod 'GoogleSignIn'

  target 'Cidaas_Tests' do
    inherit! :search_paths
    pod 'Quick', '2.2.0'
    pod 'Mockingjay', '3.0.0-alpha.1'
  end
end
