use_frameworks!

target 'Cidaas_Example' do
  pod 'Cidaas', :path => '../'
  pod 'SDWebImage', '~> 4.4'
  pod 'SCLAlertView'
  pod 'IQKeyboardManagerSwift', '~> 5.0.3'

  target 'Cidaas_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Mockingjay', '~> 2.0'
  end
end
