stages:
  - test

code_quality_json:
  image: docker:git
  stage: test
  allow_failure: true
  variables:
    CODE_QUALITY_IMAGE: "codeclimate/codeclimate:latest"
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    - docker run 
       --env SOURCE_CODE="$PWD"
       --env CODECLIMATE_CODE="$PWD"
       --volume "$PWD":/code 
       --volume /var/run/docker.sock:/var/run/docker.sock 
       --volume /tmp/cc:/tmp/cc 
       "$CODE_QUALITY_IMAGE" analyze -f json > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
  dependencies: []
