# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - cd Example
  - xcodebuild test -workspace Cidaas.xcworkspace -scheme Cidaas -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -enableCodeCoverage YES | xcpretty -s
  - bash <(curl -s https://codecov.io/bash) -cF ios
