# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
  - cd Example
  - sudo gem install cocoapods
  - pod update
script:
  - xcodebuild test -workspace Cidaas.xcworkspace -scheme Cidaas -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' -enableCodeCoverage YES | xcpretty -s
  - cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 000fddc0-7c1f-475d-9f1b-e0165de5f569
